const { User, Product, Cart } = require('../models');

const seedData = async () => {
  try {
    // Check if products already exist
    const productCount = await Product.count();
    if (productCount > 0) {
      console.log('⚠️ Products already exist. Skipping seeding.');
      console.log('To re-seed, truncate the "Products" table first.');

      // Still create users if they don't exist
      const userCount = await User.count();
      if (userCount === 0) {
        console.log('🌱 Creating default users...');
        const admin = await User.create({
          name: 'Admin User',
          email: 'admin@shopwave.com',
          password: 'admin123',
          role: 'admin',
        });
        await Cart.create({ userId: admin.id });

        const user = await User.create({
          name: 'John Doe',
          email: 'user@shopwave.com',
          password: 'user123',
          role: 'user',
        });
        await Cart.create({ userId: user.id });
        console.log('✅ Users created.');
      }
      return;
    }

    console.log('🌱 Seeding 50 realistic products...');

    // Create users
    const admin = await User.create({
      name: 'Admin User',
      email: 'admin@shopwave.com',
      password: 'admin123',
      role: 'admin',
    });
    await Cart.create({ userId: admin.id });

    const user = await User.create({
      name: 'John Doe',
      email: 'user@shopwave.com',
      password: 'user123',
      role: 'user',
    });
    await Cart.create({ userId: user.id });

    // ===================== REAL PRODUCTS =====================
    const products = [
      // Electronics (15 products)
      {
        name: 'Apple iPhone 15 Pro Max (256GB) - Natural Titanium',
        description: 'Latest Apple iPhone with A17 Pro chip, titanium design, 48MP camera, and 5x optical zoom.',
        price: 139900,
        stock: 25,
        category: 'Electronics',
        brand: 'Apple',
        featured: true,
        rating: 4.8,
        numReviews: 124,
        image: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400&q=80',
        color: 'Natural Titanium',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Samsung Galaxy S24 Ultra (512GB) - Titanium Black',
        description: '6.8" Dynamic AMOLED, 200MP camera, S Pen included, Snapdragon 8 Gen 3.',
        price: 124999,
        stock: 30,
        category: 'Electronics',
        brand: 'Samsung',
        featured: true,
        rating: 4.7,
        numReviews: 89,
        image: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400&q=80',
        color: 'Titanium Black',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'MacBook Pro 16" (2024) - M3 Max Chip, 32GB RAM, 1TB SSD',
        description: 'Apple M3 Max chip with 16-core CPU, 40-core GPU, 16-core Neural Engine.',
        price: 299990,
        stock: 15,
        category: 'Electronics',
        brand: 'Apple',
        featured: true,
        rating: 4.9,
        numReviews: 56,
        image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&q=80',
        color: 'Space Gray',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
        description: 'Industry-leading noise cancellation with 30-hour battery life and exceptional audio quality.',
        price: 29990,
        stock: 50,
        category: 'Electronics',
        brand: 'Sony',
        featured: false,
        rating: 4.7,
        numReviews: 203,
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&q=80',
        color: 'Black',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Apple Watch Series 9 (GPS, 45mm) - Midnight Aluminum',
        description: 'Always-On Retina display, S9 SiP, double tap gesture, crash detection.',
        price: 45900,
        stock: 40,
        category: 'Electronics',
        brand: 'Apple',
        featured: false,
        rating: 4.6,
        numReviews: 78,
        image: 'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=400&q=80',
        color: 'Midnight',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Samsung 65" 4K Neo QLED TV (QN90C)',
        description: 'Quantum Matrix Technology, Neo Quantum Processor 4K, 100% color volume.',
        price: 219990,
        stock: 12,
        category: 'Electronics',
        brand: 'Samsung',
        featured: true,
        rating: 4.5,
        numReviews: 34,
        image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829e1?w=400&q=80',
        color: 'Black',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Canon EOS R5 Mirrorless Camera (Body Only)',
        description: '45MP full-frame sensor, 8K RAW video, 20 fps electronic shutter.',
        price: 389990,
        stock: 8,
        category: 'Electronics',
        brand: 'Canon',
        featured: true,
        rating: 4.9,
        numReviews: 42,
        image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&q=80',
        color: 'Black',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Sony PlayStation 5 Console (Disc Edition)',
        description: 'Ultra-high-speed SSD, 3D audio, haptic feedback, adaptive triggers.',
        price: 54990,
        stock: 20,
        category: 'Electronics',
        brand: 'Sony',
        featured: true,
        rating: 4.9,
        numReviews: 1204,
        image: 'https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=400&q=80',
        color: 'White',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Dell XPS 15 (2024) - Intel Core i9, 32GB RAM, 1TB SSD, RTX 4060',
        description: '15.6" 3.5K OLED InfinityEdge display, premium build, powerful performance.',
        price: 249990,
        stock: 10,
        category: 'Electronics',
        brand: 'Dell',
        featured: false,
        rating: 4.7,
        numReviews: 28,
        image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400&q=80',
        color: 'Platinum Silver',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Bose QuietComfort Ultra Wireless Headphones',
        description: 'Immersive audio with spatial sound, world-class noise cancellation.',
        price: 34900,
        stock: 35,
        category: 'Electronics',
        brand: 'Bose',
        featured: false,
        rating: 4.6,
        numReviews: 87,
        image: 'https://images.unsplash.com/photo-1546435770-a3e5d0f6e6e5?w=400&q=80',
        color: 'Black',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'iPad Pro 12.9" (2024) - M4 Chip, 256GB, Wi-Fi',
        description: 'Ultra Retina XDR display, M4 chip with 10-core GPU, Thunderbolt support.',
        price: 119900,
        stock: 22,
        category: 'Electronics',
        brand: 'Apple',
        featured: true,
        rating: 4.8,
        numReviews: 63,
        image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&q=80',
        color: 'Silver',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Google Pixel 8 Pro (128GB) - Bay Blue',
        description: 'Google Tensor G3, 50MP camera with AI features, 7 years of updates.',
        price: 84999,
        stock: 18,
        category: 'Electronics',
        brand: 'Google',
        featured: false,
        rating: 4.5,
        numReviews: 41,
        image: 'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=400&q=80',
        color: 'Bay Blue',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'OnePlus 12 (16GB RAM, 512GB) - Flowy Emerald',
        description: 'Snapdragon 8 Gen 3, 120Hz ProXDR display, 100W fast charging.',
        price: 64999,
        stock: 30,
        category: 'Electronics',
        brand: 'OnePlus',
        featured: false,
        rating: 4.4,
        numReviews: 52,
        image: 'https://images.unsplash.com/photo-1586056145266-1f4d8e8b9f5a?w=400&q=80',
        color: 'Flowy Emerald',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'JBL Flip 6 Portable Bluetooth Speaker',
        description: '80W output, 12 hours playtime, waterproof, partyBoost compatible.',
        price: 11999,
        stock: 60,
        category: 'Electronics',
        brand: 'JBL',
        featured: false,
        rating: 4.5,
        numReviews: 215,
        image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&q=80',
        color: 'Black',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'LG 27" UltraGear 4K Gaming Monitor (27GP95R)',
        description: '4K Nano IPS, 160Hz refresh rate, 1ms response, G-Sync compatible.',
        price: 59990,
        stock: 14,
        category: 'Electronics',
        brand: 'LG',
        featured: false,
        rating: 4.6,
        numReviews: 23,
        image: 'https://images.unsplash.com/photo-1586210579191-33b45e38fa2c?w=400&q=80',
        color: 'Black',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },

      // Clothing (10 products)
      {
        name: 'Nike Air Max 270 (Men) - Black/White',
        description: 'Comfortable sneakers with visible Air unit in the heel for all-day cushioning.',
        price: 14995,
        stock: 100,
        category: 'Clothing',
        brand: 'Nike',
        featured: true,
        rating: 4.5,
        numReviews: 312,
        image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80',
        color: 'Black/White',
        size: '8,9,10,11',
        fabric: 'Synthetic',
        occasion: 'Sports',
        gender: 'Men',
      },
      {
        name: 'Levi\'s 501 Original Fit Jeans (Men) - Dark Blue',
        description: 'Classic straight-leg jeans with button fly and 100% cotton denim.',
        price: 5999,
        stock: 150,
        category: 'Clothing',
        brand: 'Levis',
        featured: false,
        rating: 4.3,
        numReviews: 456,
        image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&q=80',
        color: 'Dark Blue',
        size: '30,32,34,36',
        fabric: 'Denim',
        occasion: 'Casual',
        gender: 'Men',
      },
      {
        name: 'Adidas Ultraboost 22 (Women) - Core Black',
        description: 'Responsive running shoes with adidas Primeknit upper and Boost midsole.',
        price: 16999,
        stock: 80,
        category: 'Clothing',
        brand: 'Adidas',
        featured: true,
        rating: 4.6,
        numReviews: 189,
        image: 'https://images.unsplash.com/photo-1608231387042-66d8b9924b6e?w=400&q=80',
        color: 'Core Black',
        size: '6,7,8,9',
        fabric: 'Primeknit',
        occasion: 'Sports',
        gender: 'Women',
      },
      {
        name: 'H&M Oversized Hoodie (Unisex) - Grey Melange',
        description: 'Comfortable cotton-blend hoodie with kangaroo pocket and adjustable hood.',
        price: 2499,
        stock: 200,
        category: 'Clothing',
        brand: 'H&M',
        featured: false,
        rating: 4.2,
        numReviews: 134,
        image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400&q=80',
        color: 'Grey',
        size: 'S,M,L,XL',
        fabric: 'Cotton',
        occasion: 'Casual',
        gender: 'Unisex',
      },
      {
        name: 'Zara Tailored Blazer (Women) - Beige',
        description: 'Elegant single-breasted blazer with notched lapels and long sleeves.',
        price: 7999,
        stock: 40,
        category: 'Clothing',
        brand: 'Zara',
        featured: false,
        rating: 4.4,
        numReviews: 67,
        image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400&q=80',
        color: 'Beige',
        size: 'XS,S,M,L',
        fabric: 'Polyester',
        occasion: 'Formal',
        gender: 'Women',
      },
      {
        name: 'Puma Ferrari Drift Cat 5 (Men) - Red/Black',
        description: 'Sleek driving shoes inspired by Ferrari, synthetic leather upper.',
        price: 7995,
        stock: 55,
        category: 'Clothing',
        brand: 'Puma',
        featured: false,
        rating: 4.3,
        numReviews: 42,
        image: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?w=400&q=80',
        color: 'Red/Black',
        size: '8,9,10,11',
        fabric: 'Synthetic',
        occasion: 'Sports',
        gender: 'Men',
      },
      {
        name: 'The North Face Nuptse 1996 Jacket (Unisex) - Black',
        description: 'Iconic puffer jacket with 700-fill goose down, water-resistant.',
        price: 27999,
        stock: 30,
        category: 'Clothing',
        brand: 'The North Face',
        featured: true,
        rating: 4.8,
        numReviews: 93,
        image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&q=80',
        color: 'Black',
        size: 'S,M,L,XL',
        fabric: 'Nylon',
        occasion: 'Outdoor',
        gender: 'Unisex',
      },
      {
        name: 'Calvin Klein Women\'s Sheath Dress - Navy Blue',
        description: 'Classic sleeveless sheath dress with back zipper, perfect for office.',
        price: 8999,
        stock: 25,
        category: 'Clothing',
        brand: 'Calvin Klein',
        featured: false,
        rating: 4.3,
        numReviews: 28,
        image: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=400&q=80',
        color: 'Navy',
        size: 'XS,S,M,L',
        fabric: 'Polyester',
        occasion: 'Formal',
        gender: 'Women',
      },
      {
        name: 'Tommy Hilfiger Men\'s Polo Shirt - Dark Red',
        description: 'Classic fit cotton pique polo with embroidered flag logo.',
        price: 3999,
        stock: 120,
        category: 'Clothing',
        brand: 'Tommy Hilfiger',
        featured: false,
        rating: 4.4,
        numReviews: 156,
        image: 'https://images.unsplash.com/photo-1589310243389-96a5483213a8?w=400&q=80',
        color: 'Dark Red',
        size: 'S,M,L,XL',
        fabric: 'Cotton',
        occasion: 'Casual',
        gender: 'Men',
      },
      {
        name: 'Under Armour HeatGear Leggings (Women) - Black',
        description: 'High-performance leggings with moisture-wicking and four-way stretch.',
        price: 3499,
        stock: 85,
        category: 'Clothing',
        brand: 'Under Armour',
        featured: false,
        rating: 4.5,
        numReviews: 78,
        image: 'https://images.unsplash.com/photo-1506624437116-b6b4f0b9f2f5?w=400&q=80',
        color: 'Black',
        size: 'XS,S,M,L',
        fabric: 'Spandex',
        occasion: 'Sports',
        gender: 'Women',
      },

      // Kitchen (8 products)
      {
        name: 'Instant Pot Duo 7-in-1 6Qt Pressure Cooker',
        description: 'Multi-use cooker that replaces 7 appliances: pressure cooker, slow cooker, rice cooker, steamer, saute, yogurt maker, warmer.',
        price: 10999,
        stock: 60,
        category: 'Kitchen',
        brand: 'Instant Pot',
        featured: true,
        rating: 4.6,
        numReviews: 892,
        image: 'https://images.unsplash.com/photo-1585515320310-259814833e62?w=400&q=80',
        color: 'Stainless Steel',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Prestige Omega Deluxe Aluminium Pressure Cooker (5L)',
        description: 'Hard anodized body, secure locking lid, energy efficient.',
        price: 3999,
        stock: 80,
        category: 'Kitchen',
        brand: 'Prestige',
        featured: false,
        rating: 4.5,
        numReviews: 234,
        image: 'https://images.unsplash.com/photo-1590434991368-73f3d2e5e0a5?w=400&q=80',
        color: 'Silver',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'KitchenAid 5 Quart Stand Mixer - Empire Red',
        description: 'Iconic tilt-head design, 10 speeds, planetary mixing action.',
        price: 37990,
        stock: 20,
        category: 'Kitchen',
        brand: 'KitchenAid',
        featured: true,
        rating: 4.9,
        numReviews: 145,
        image: 'https://images.unsplash.com/photo-1584269600516-0932f6f9f1c3?w=400&q=80',
        color: 'Red',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Cuisinart 14-Cup Food Processor',
        description: 'Supreme-wide feed tube, stainless steel slicing and shredding discs.',
        price: 18999,
        stock: 25,
        category: 'Kitchen',
        brand: 'Cuisinart',
        featured: false,
        rating: 4.7,
        numReviews: 89,
        image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&q=80',
        color: 'Stainless Steel',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Hawkins Futura Hard Anodised Pressure Cooker (3L)',
        description: 'Even heat distribution, thick bottom, easy to clean.',
        price: 2995,
        stock: 100,
        category: 'Kitchen',
        brand: 'Hawkins',
        featured: false,
        rating: 4.4,
        numReviews: 178,
        image: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=400&q=80',
        color: 'Grey',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Philips Air Fryer XXL (HD9867)',
        description: 'Rapid Air technology, 7.2L capacity, fat removal, smart cooking programs.',
        price: 17999,
        stock: 35,
        category: 'Kitchen',
        brand: 'Philips',
        featured: true,
        rating: 4.6,
        numReviews: 267,
        image: 'https://images.unsplash.com/photo-1624388836434-5d5f1b5f9b3a?w=400&q=80',
        color: 'Black',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Cello Butterfly 3-Litre Stainless Steel Pressure Cooker',
        description: 'Vulcan base for even heating, ergonomic handles, safety lock.',
        price: 2199,
        stock: 150,
        category: 'Kitchen',
        brand: 'Cello',
        featured: false,
        rating: 4.2,
        numReviews: 312,
        image: 'https://images.unsplash.com/photo-1584269600476-0b9b5a5a5a5a?w=400&q=80',
        color: 'Silver',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Borosil 6-Piece Stainless Steel Cookware Set',
        description: 'Includes 2 saucepans, 2 fry pans, and lids. Induction compatible.',
        price: 5499,
        stock: 40,
        category: 'Kitchen',
        brand: 'Borosil',
        featured: false,
        rating: 4.3,
        numReviews: 67,
        image: 'https://images.unsplash.com/photo-1584269600521-3b1b3c2b6b6b?w=400&q=80',
        color: 'Silver',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },

      // Sports (7 products)
      {
        name: 'Yonex Nanoray 20i Badminton Racket (Unstrung)',
        description: 'Lightweight, head-light balance for quick maneuverability.',
        price: 2999,
        stock: 50,
        category: 'Sports',
        brand: 'Yonex',
        featured: false,
        rating: 4.4,
        numReviews: 89,
        image: 'https://images.unsplash.com/photo-1626224583764-f9b6d4c3b3f3?w=400&q=80',
        color: 'Blue',
        size: null,
        fabric: null,
        occasion: 'Sports',
        gender: 'Unisex',
      },
      {
        name: 'Cosco 5kg PVC Vinyl Dumbbell Set (Pair)',
        description: 'Vinyl coated, non-slip grip, ideal for home workouts.',
        price: 1499,
        stock: 120,
        category: 'Sports',
        brand: 'Cosco',
        featured: false,
        rating: 4.3,
        numReviews: 156,
        image: 'https://images.unsplash.com/photo-1586401100295-7a8096fd3b3f?w=400&q=80',
        color: 'Black',
        size: null,
        fabric: null,
        occasion: 'Workout',
        gender: 'Unisex',
      },
      {
        name: 'Nike Premier League Football (Size 5)',
        description: 'Machine-stitched casing, high-contrast graphics for visibility.',
        price: 3499,
        stock: 80,
        category: 'Sports',
        brand: 'Nike',
        featured: true,
        rating: 4.5,
        numReviews: 203,
        image: 'https://images.unsplash.com/photo-1614632537423-0e6c7e5b8f3f?w=400&q=80',
        color: 'White',
        size: null,
        fabric: null,
        occasion: 'Sports',
        gender: 'Unisex',
      },
      {
        name: 'Decathlon Quechua 2-Person Waterproof Tent',
        description: 'Easy setup, waterproof up to 2000mm, UV protection.',
        price: 3999,
        stock: 25,
        category: 'Sports',
        brand: 'Decathlon',
        featured: false,
        rating: 4.2,
        numReviews: 67,
        image: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=400&q=80',
        color: 'Green',
        size: null,
        fabric: 'Polyester',
        occasion: 'Camping',
        gender: 'Unisex',
      },
      {
        name: 'Head Graphene 360+ Radical MP Tennis Racquet',
        description: 'For intermediate to advanced players, 300g unstrung weight.',
        price: 18999,
        stock: 15,
        category: 'Sports',
        brand: 'Head',
        featured: false,
        rating: 4.7,
        numReviews: 34,
        image: 'https://images.unsplash.com/photo-1617083277887-2d7c5f0b9f6b?w=400&q=80',
        color: 'Orange',
        size: null,
        fabric: null,
        occasion: 'Sports',
        gender: 'Unisex',
      },
      {
        name: 'Fitbit Charge 6 Fitness Tracker',
        description: 'Heart rate monitoring, GPS, sleep tracking, 7-day battery.',
        price: 13999,
        stock: 45,
        category: 'Sports',
        brand: 'Fitbit',
        featured: true,
        rating: 4.5,
        numReviews: 112,
        image: 'https://images.unsplash.com/photo-1576243345690-4e4b79b9e6c7?w=400&q=80',
        color: 'Black',
        size: null,
        fabric: null,
        occasion: 'Sports',
        gender: 'Unisex',
      },
      {
        name: 'Adidas Performance Backpack (Medium)',
        description: 'Water-resistant, padded laptop sleeve, adjustable shoulder straps.',
        price: 2999,
        stock: 60,
        category: 'Sports',
        brand: 'Adidas',
        featured: false,
        rating: 4.3,
        numReviews: 89,
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80',
        color: 'Black',
        size: null,
        fabric: 'Polyester',
        occasion: 'Sports',
        gender: 'Unisex',
      },

      // Furniture (5 products)
      {
        name: 'IKEA MALM Bed Frame with Storage (Queen)',
        description: 'High bed frame with 2 large storage boxes underneath, white.',
        price: 29990,
        stock: 10,
        category: 'Furniture',
        brand: 'IKEA',
        featured: true,
        rating: 4.5,
        numReviews: 78,
        image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400&q=80',
        color: 'White',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Wakefit Orthopaedic Memory Foam Mattress (Queen)',
        description: 'Medium firm, pressure-relieving memory foam, 10-year warranty.',
        price: 14999,
        stock: 30,
        category: 'Furniture',
        brand: 'Wakefit',
        featured: true,
        rating: 4.6,
        numReviews: 234,
        image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400&q=80',
        color: 'White',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Green Soul Beast Gaming Chair (Black/Red)',
        description: 'Ergonomic, lumbar support, recline up to 180°, adjustable armrests.',
        price: 15999,
        stock: 25,
        category: 'Furniture',
        brand: 'Green Soul',
        featured: false,
        rating: 4.4,
        numReviews: 56,
        image: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=400&q=80',
        color: 'Black/Red',
        size: null,
        fabric: 'PU Leather',
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Durian 3-Seater Fabric Sofa (Grey)',
        description: 'Solid wood frame, high-resilience foam, removable covers.',
        price: 39990,
        stock: 8,
        category: 'Furniture',
        brand: 'Durian',
        featured: false,
        rating: 4.3,
        numReviews: 42,
        image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80',
        color: 'Grey',
        size: null,
        fabric: 'Fabric',
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Urban Ladder Solace Study Table (Brown)',
        description: 'Engineered wood, 2 drawers, cable management, modern design.',
        price: 12999,
        stock: 20,
        category: 'Furniture',
        brand: 'Urban Ladder',
        featured: false,
        rating: 4.4,
        numReviews: 38,
        image: 'https://images.unsplash.com/photo-1518455027359-f3f8164d1b7c?w=400&q=80',
        color: 'Brown',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },

      // Home (5 products)
      {
        name: 'Dyson V15 Detect Cordless Vacuum Cleaner',
        description: 'Laser dust detection, advanced filtration, 60-minute runtime.',
        price: 54999,
        stock: 15,
        category: 'Home',
        brand: 'Dyson',
        featured: true,
        rating: 4.8,
        numReviews: 143,
        image: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=400&q=80',
        color: 'Yellow',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Philips HL1643 Mixer Grinder (750W)',
        description: '4 stainless steel jars, turbo boost, fruit filter.',
        price: 5999,
        stock: 50,
        category: 'Home',
        brand: 'Philips',
        featured: false,
        rating: 4.5,
        numReviews: 267,
        image: 'https://images.unsplash.com/photo-1584269600521-3b1b3c2b6b6b?w=400&q=80',
        color: 'Black',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Bajaj Flashy 1200W Dry Iron',
        description: 'Non-stick coating, 360° swivel cord, thermostat control.',
        price: 799,
        stock: 200,
        category: 'Home',
        brand: 'Bajaj',
        featured: false,
        rating: 4.2,
        numReviews: 567,
        image: 'https://images.unsplash.com/photo-1584269600521-3b1b3c2b6b6b?w=400&q=80',
        color: 'Blue',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Prestige PFTGM 01 Gas Stove (4 Burner)',
        description: 'Toughened glass top, brass burners, auto-ignition.',
        price: 6999,
        stock: 30,
        category: 'Home',
        brand: 'Prestige',
        featured: false,
        rating: 4.4,
        numReviews: 89,
        image: 'https://images.unsplash.com/photo-1584269600521-3b1b3c2b6b6b?w=400&q=80',
        color: 'Black',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Honeywell Air Purifier (HPA300)',
        description: 'For large rooms, 3-in-1 HEPA filter, 4 fan speeds.',
        price: 24999,
        stock: 12,
        category: 'Home',
        brand: 'Honeywell',
        featured: true,
        rating: 4.6,
        numReviews: 78,
        image: 'https://images.unsplash.com/photo-1584269600521-3b1b3c2b6b6b?w=400&q=80',
        color: 'White',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      // ========== ADD THESE 50 NEW PRODUCTS TO YOUR EXISTING seedData.js ==========
      // In the products array, after the first 50 products, paste the following:

      // ---------- Additional 15 Electronics Products ----------
      {
        name: 'Apple iPhone 14 (128GB) - Midnight',
        description: '6.1" Super Retina XDR display, A15 Bionic chip, dual-camera system.',
        price: 79900,
        stock: 45,
        category: 'Electronics',
        brand: 'Apple',
        featured: false,
        rating: 4.6,
        numReviews: 312,
        image: 'https://images.unsplash.com/photo-1678658757838-9e4b6c1e5b1b?w=400&q=80',
        color: 'Midnight',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Samsung Galaxy Z Fold 5 (512GB) - Icy Blue',
        description: '7.6" foldable Dynamic AMOLED, multitasking powerhouse, S Pen support.',
        price: 154999,
        stock: 12,
        category: 'Electronics',
        brand: 'Samsung',
        featured: true,
        rating: 4.7,
        numReviews: 78,
        image: 'https://images.unsplash.com/photo-1678658757838-9e4b6c1e5b1b?w=400&q=80',
        color: 'Icy Blue',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Google Pixel 7 (128GB) - Obsidian',
        description: 'Google Tensor G2, 50MP dual camera, Titan M2 security chip.',
        price: 59999,
        stock: 40,
        category: 'Electronics',
        brand: 'Google',
        featured: false,
        rating: 4.4,
        numReviews: 156,
        image: 'https://images.unsplash.com/photo-1678658757838-9e4b6c1e5b1b?w=400&q=80',
        color: 'Obsidian',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'OnePlus Nord 3 (256GB) - Misty Green',
        description: 'Dimensity 9000, 120Hz Fluid AMOLED, 80W fast charging.',
        price: 34999,
        stock: 60,
        category: 'Electronics',
        brand: 'OnePlus',
        featured: false,
        rating: 4.5,
        numReviews: 203,
        image: 'https://images.unsplash.com/photo-1678658757838-9e4b6c1e5b1b?w=400&q=80',
        color: 'Misty Green',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Xiaomi Mi 11 (128GB) - Horizon Blue',
        description: 'Snapdragon 888, 108MP triple camera, 55W fast charging.',
        price: 39999,
        stock: 55,
        category: 'Electronics',
        brand: 'Xiaomi',
        featured: false,
        rating: 4.3,
        numReviews: 178,
        image: 'https://images.unsplash.com/photo-1678658757838-9e4b6c1e5b1b?w=400&q=80',
        color: 'Horizon Blue',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Realme GT 2 Pro (256GB) - Paper White',
        description: 'Snapdragon 8 Gen 1, 120Hz AMOLED, 50MP dual camera.',
        price: 37999,
        stock: 35,
        category: 'Electronics',
        brand: 'Realme',
        featured: false,
        rating: 4.4,
        numReviews: 92,
        image: 'https://images.unsplash.com/photo-1678658757838-9e4b6c1e5b1b?w=400&q=80',
        color: 'Paper White',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Sony Xperia 1 V (256GB) - Black',
        description: '6.5" 4K OLED, Snapdragon 8 Gen 2, pro camera features.',
        price: 119999,
        stock: 10,
        category: 'Electronics',
        brand: 'Sony',
        featured: true,
        rating: 4.6,
        numReviews: 34,
        image: 'https://images.unsplash.com/photo-1678658757838-9e4b6c1e5b1b?w=400&q=80',
        color: 'Black',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'LG C3 55" 4K OLED TV',
        description: 'Self-lit OLED, α9 Gen6 AI processor, Dolby Vision, Game Optimizer.',
        price: 169990,
        stock: 8,
        category: 'Electronics',
        brand: 'LG',
        featured: true,
        rating: 4.8,
        numReviews: 45,
        image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829e1?w=400&q=80',
        color: 'Black',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Sony Bravia XR 65" 4K OLED TV',
        description: 'Cognitive Processor XR, XR OLED Contrast, Acoustic Surface Audio+.',
        price: 249990,
        stock: 6,
        category: 'Electronics',
        brand: 'Sony',
        featured: true,
        rating: 4.9,
        numReviews: 28,
        image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829e1?w=400&q=80',
        color: 'Black',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Apple iPad Air (5th Gen) 64GB Wi-Fi',
        description: '10.9" Liquid Retina, M1 chip, 12MP Wide camera, Landscape stereo speakers.',
        price: 59900,
        stock: 30,
        category: 'Electronics',
        brand: 'Apple',
        featured: false,
        rating: 4.7,
        numReviews: 112,
        image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&q=80',
        color: 'Space Gray',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Samsung Galaxy Tab S9 Ultra (512GB)',
        description: '14.6" Dynamic AMOLED 2X, Snapdragon 8 Gen 2, S Pen included.',
        price: 119999,
        stock: 15,
        category: 'Electronics',
        brand: 'Samsung',
        featured: true,
        rating: 4.8,
        numReviews: 67,
        image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&q=80',
        color: 'Graphite',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Microsoft Surface Laptop 5 (13.5")',
        description: '12th Gen Intel Core i7, 16GB RAM, 512GB SSD, Windows 11.',
        price: 149990,
        stock: 12,
        category: 'Electronics',
        brand: 'Microsoft',
        featured: false,
        rating: 4.5,
        numReviews: 42,
        image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400&q=80',
        color: 'Platinum',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'HP Spectre x360 14 (2024)',
        description: 'Intel Core i7, 16GB RAM, 1TB SSD, 3K OLED touchscreen.',
        price: 179990,
        stock: 9,
        category: 'Electronics',
        brand: 'HP',
        featured: false,
        rating: 4.6,
        numReviews: 23,
        image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400&q=80',
        color: 'Nightfall Black',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Lenovo ThinkPad X1 Carbon (Gen 11)',
        description: '13th Gen Intel Core i7, 16GB RAM, 512GB SSD, lightweight business laptop.',
        price: 169990,
        stock: 11,
        category: 'Electronics',
        brand: 'Lenovo',
        featured: false,
        rating: 4.7,
        numReviews: 31,
        image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400&q=80',
        color: 'Black',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Asus ROG Strix G16 Gaming Laptop',
        description: 'Intel Core i9, 16GB RAM, 1TB SSD, RTX 4070, 16" 240Hz display.',
        price: 219990,
        stock: 7,
        category: 'Electronics',
        brand: 'Asus',
        featured: true,
        rating: 4.8,
        numReviews: 52,
        image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400&q=80',
        color: 'Eclipse Gray',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },

      // ---------- Additional 10 Clothing Products ----------
      {
        name: 'Puma RS-X³ Sneakers (Men) - White/Red',
        description: 'Chunky retro sneakers with mesh and leather upper, softfoam+ sock.',
        price: 8995,
        stock: 60,
        category: 'Clothing',
        brand: 'Puma',
        featured: false,
        rating: 4.4,
        numReviews: 112,
        image: 'https://images.unsplash.com/photo-1608231387042-66d8b9924b6e?w=400&q=80',
        color: 'White/Red',
        size: '8,9,10,11',
        fabric: 'Synthetic',
        occasion: 'Casual',
        gender: 'Men',
      },
      {
        name: 'Reebok Classic Leather (Women) - White',
        description: 'Timeless sneakers with soft leather upper and EVA midsole.',
        price: 6995,
        stock: 70,
        category: 'Clothing',
        brand: 'Reebok',
        featured: false,
        rating: 4.5,
        numReviews: 98,
        image: 'https://images.unsplash.com/photo-1608231387042-66d8b9924b6e?w=400&q=80',
        color: 'White',
        size: '6,7,8,9',
        fabric: 'Leather',
        occasion: 'Casual',
        gender: 'Women',
      },
      {
        name: 'Vans Old Skool (Unisex) - Black/White',
        description: 'Classic skate shoes with suede and canvas upper, padded collar.',
        price: 5999,
        stock: 90,
        category: 'Clothing',
        brand: 'Vans',
        featured: true,
        rating: 4.6,
        numReviews: 234,
        image: 'https://images.unsplash.com/photo-1608231387042-66d8b9924b6e?w=400&q=80',
        color: 'Black/White',
        size: '7,8,9,10,11',
        fabric: 'Canvas',
        occasion: 'Casual',
        gender: 'Unisex',
      },
      {
        name: 'Converse Chuck Taylor All Star (Unisex) - Black',
        description: 'Iconic high-top canvas sneakers with rubber toe cap.',
        price: 4999,
        stock: 120,
        category: 'Clothing',
        brand: 'Converse',
        featured: false,
        rating: 4.5,
        numReviews: 345,
        image: 'https://images.unsplash.com/photo-1608231387042-66d8b9924b6e?w=400&q=80',
        color: 'Black',
        size: '7,8,9,10,11',
        fabric: 'Canvas',
        occasion: 'Casual',
        gender: 'Unisex',
      },
      {
        name: 'H&M Slim Fit Jeans (Men) - Light Blue',
        description: 'Stretch denim jeans with slim fit and five-pocket styling.',
        price: 2999,
        stock: 110,
        category: 'Clothing',
        brand: 'H&M',
        featured: false,
        rating: 4.2,
        numReviews: 178,
        image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&q=80',
        color: 'Light Blue',
        size: '30,32,34,36',
        fabric: 'Denim',
        occasion: 'Casual',
        gender: 'Men',
      },
      {
        name: 'Zara Cropped Trousers (Women) - Black',
        description: 'High-waisted cropped trousers with front pleats and zip fly.',
        price: 3999,
        stock: 45,
        category: 'Clothing',
        brand: 'Zara',
        featured: false,
        rating: 4.3,
        numReviews: 67,
        image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400&q=80',
        color: 'Black',
        size: 'XS,S,M,L',
        fabric: 'Polyester',
        occasion: 'Formal',
        gender: 'Women',
      },
      {
        name: 'Uniqlo AIRism Cotton T-Shirt (Men) - White',
        description: 'Breathable, soft cotton tee with AIRism technology for comfort.',
        price: 1490,
        stock: 200,
        category: 'Clothing',
        brand: 'Uniqlo',
        featured: false,
        rating: 4.4,
        numReviews: 267,
        image: 'https://images.unsplash.com/photo-1589310243389-96a5483213a8?w=400&q=80',
        color: 'White',
        size: 'S,M,L,XL',
        fabric: 'Cotton',
        occasion: 'Casual',
        gender: 'Men',
      },
      {
        name: 'Gap Logo Hoodie (Unisex) - Navy',
        description: 'Classic fleece hoodie with embroidered Gap logo, kangaroo pocket.',
        price: 3499,
        stock: 80,
        category: 'Clothing',
        brand: 'Gap',
        featured: false,
        rating: 4.3,
        numReviews: 123,
        image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400&q=80',
        color: 'Navy',
        size: 'S,M,L,XL',
        fabric: 'Fleece',
        occasion: 'Casual',
        gender: 'Unisex',
      },
      {
        name: 'Tommy Hilfiger Lightweight Jacket (Men) - Olive',
        description: 'Water-resistant nylon jacket with Tommy Hilfiger flag embroidery.',
        price: 8999,
        stock: 35,
        category: 'Clothing',
        brand: 'Tommy Hilfiger',
        featured: false,
        rating: 4.5,
        numReviews: 56,
        image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&q=80',
        color: 'Olive',
        size: 'S,M,L,XL',
        fabric: 'Nylon',
        occasion: 'Outdoor',
        gender: 'Men',
      },
      {
        name: 'Calvin Klein Cotton Stretch Boxer Briefs (3-Pack) - Black',
        description: 'Soft cotton stretch boxer briefs with signature waistband.',
        price: 2999,
        stock: 150,
        category: 'Clothing',
        brand: 'Calvin Klein',
        featured: false,
        rating: 4.6,
        numReviews: 412,
        image: 'https://images.unsplash.com/photo-1589310243389-96a5483213a8?w=400&q=80',
        color: 'Black',
        size: 'S,M,L,XL',
        fabric: 'Cotton',
        occasion: 'Casual',
        gender: 'Men',
      },

      // ---------- Additional 8 Kitchen Products ----------
      {
        name: 'Prestige Induction Cooktop (2100W)',
        description: 'Digital display, 8 power levels, auto shut-off, touch control.',
        price: 4999,
        stock: 50,
        category: 'Kitchen',
        brand: 'Prestige',
        featured: false,
        rating: 4.4,
        numReviews: 178,
        image: 'https://images.unsplash.com/photo-1584269600521-3b1b3c2b6b6b?w=400&q=80',
        color: 'Black',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Philips Electric Kettle (1.5L)',
        description: 'Stainless steel body, 360° swivel base, boil-dry protection.',
        price: 2499,
        stock: 80,
        category: 'Kitchen',
        brand: 'Philips',
        featured: false,
        rating: 4.5,
        numReviews: 234,
        image: 'https://images.unsplash.com/photo-1584269600521-3b1b3c2b6b6b?w=400&q=80',
        color: 'Silver',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Morphy Richards 2-Slice Toaster',
        description: 'Wide slots, 6 browning levels, reheat and cancel functions.',
        price: 3499,
        stock: 45,
        category: 'Kitchen',
        brand: 'Morphy Richards',
        featured: false,
        rating: 4.3,
        numReviews: 89,
        image: 'https://images.unsplash.com/photo-1584269600521-3b1b3c2b6b6b?w=400&q=80',
        color: 'Stainless Steel',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Hamilton Beach 2-Speed Hand Blender',
        description: 'Powerful 300W motor, stainless steel shaft, includes measuring cup.',
        price: 3999,
        stock: 30,
        category: 'Kitchen',
        brand: 'Hamilton Beach',
        featured: false,
        rating: 4.4,
        numReviews: 56,
        image: 'https://images.unsplash.com/photo-1584269600521-3b1b3c2b6b6b?w=400&q=80',
        color: 'Black',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'OXO Good Grips 3-Piece Kitchen Utensil Set',
        description: 'Heat-resistant nylon, comfortable non-slip handles.',
        price: 1999,
        stock: 70,
        category: 'Kitchen',
        brand: 'OXO',
        featured: false,
        rating: 4.5,
        numReviews: 112,
        image: 'https://images.unsplash.com/photo-1584269600521-3b1b3c2b6b6b?w=400&q=80',
        color: 'Black',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Pyrex 3-Piece Glass Mixing Bowl Set',
        description: 'Borosilicate glass, microwave and dishwasher safe, non-porous.',
        price: 2999,
        stock: 60,
        category: 'Kitchen',
        brand: 'Pyrex',
        featured: false,
        rating: 4.6,
        numReviews: 145,
        image: 'https://images.unsplash.com/photo-1584269600521-3b1b3c2b6b6b?w=400&q=80',
        color: 'Clear',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Milton Thermosteel Water Bottle (1L)',
        description: 'Double-wall insulation, keeps drinks hot/cold for 12 hours.',
        price: 1299,
        stock: 200,
        category: 'Kitchen',
        brand: 'Milton',
        featured: false,
        rating: 4.4,
        numReviews: 345,
        image: 'https://images.unsplash.com/photo-1584269600521-3b1b3c2b6b6b?w=400&q=80',
        color: 'Silver',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Signoraware 3-Layer Tiffin Box (Stainless Steel)',
        description: 'Leak-proof, microwave-safe plastic lid, ideal for lunch.',
        price: 1499,
        stock: 150,
        category: 'Kitchen',
        brand: 'Signoraware',
        featured: false,
        rating: 4.3,
        numReviews: 267,
        image: 'https://images.unsplash.com/photo-1584269600521-3b1b3c2b6b6b?w=400&q=80',
        color: 'Silver',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },

      // ---------- Additional 7 Sports Products ----------
      {
        name: 'Nike Elite Basketball (Size 7)',
        description: 'Official size and weight, durable rubber cover, deep channel design.',
        price: 3499,
        stock: 50,
        category: 'Sports',
        brand: 'Nike',
        featured: false,
        rating: 4.5,
        numReviews: 78,
        image: 'https://images.unsplash.com/photo-1614632537423-0e6c7e5b8f3f?w=400&q=80',
        color: 'Orange',
        size: null,
        fabric: null,
        occasion: 'Sports',
        gender: 'Unisex',
      },
      {
        name: 'Adidas Predator Edge.3 Firm Ground Boots (Men)',
        description: 'Firm ground football boots with rubber outsole and textured upper.',
        price: 8999,
        stock: 30,
        category: 'Sports',
        brand: 'Adidas',
        featured: true,
        rating: 4.6,
        numReviews: 45,
        image: 'https://images.unsplash.com/photo-1608231387042-66d8b9924b6e?w=400&q=80',
        color: 'Black/Red',
        size: '8,9,10,11',
        fabric: 'Synthetic',
        occasion: 'Sports',
        gender: 'Men',
      },
      {
        name: 'Wilson NBA Authentic Series Basketball',
        description: 'Official NBA game ball with composite leather cover.',
        price: 5999,
        stock: 25,
        category: 'Sports',
        brand: 'Wilson',
        featured: true,
        rating: 4.7,
        numReviews: 67,
        image: 'https://images.unsplash.com/photo-1614632537423-0e6c7e5b8f3f?w=400&q=80',
        color: 'Brown',
        size: null,
        fabric: null,
        occasion: 'Sports',
        gender: 'Unisex',
      },
      {
        name: 'Yonex Mavis 350 Nylon Shuttlecocks (Pack of 6)',
        description: 'High-durability nylon shuttlecocks, consistent flight.',
        price: 899,
        stock: 200,
        category: 'Sports',
        brand: 'Yonex',
        featured: false,
        rating: 4.4,
        numReviews: 312,
        image: 'https://images.unsplash.com/photo-1626224583764-f9b6d4c3b3f3?w=400&q=80',
        color: 'White',
        size: null,
        fabric: null,
        occasion: 'Sports',
        gender: 'Unisex',
      },
      {
        name: 'Cosco PVC Dumbbell Set (10kg Pair)',
        description: 'PVC coated, comfortable grip, ideal for home workouts.',
        price: 2499,
        stock: 60,
        category: 'Sports',
        brand: 'Cosco',
        featured: false,
        rating: 4.3,
        numReviews: 89,
        image: 'https://images.unsplash.com/photo-1586401100295-7a8096fd3b3f?w=400&q=80',
        color: 'Black',
        size: null,
        fabric: null,
        occasion: 'Workout',
        gender: 'Unisex',
      },
      {
        name: 'Puma Evospeed Sprint Running Shoes (Men)',
        description: 'Lightweight sprint spikes for track events.',
        price: 7995,
        stock: 20,
        category: 'Sports',
        brand: 'Puma',
        featured: false,
        rating: 4.5,
        numReviews: 34,
        image: 'https://images.unsplash.com/photo-1608231387042-66d8b9924b6e?w=400&q=80',
        color: 'Yellow/Black',
        size: '8,9,10,11',
        fabric: 'Synthetic',
        occasion: 'Sports',
        gender: 'Men',
      },
      {
        name: 'Speedo Swim Goggles (Unisex)',
        description: 'Anti-fog, UV protection, comfortable silicone seal.',
        price: 1499,
        stock: 100,
        category: 'Sports',
        brand: 'Speedo',
        featured: false,
        rating: 4.4,
        numReviews: 178,
        image: 'https://images.unsplash.com/photo-1626224583764-f9b6d4c3b3f3?w=400&q=80',
        color: 'Blue',
        size: null,
        fabric: null,
        occasion: 'Sports',
        gender: 'Unisex',
      },

      // ---------- Additional 5 Furniture Products ----------
      {
        name: 'Wakefit Orthopaedic Queen Size Mattress',
        description: 'Medium firm, pressure-relieving memory foam, 10-year warranty.',
        price: 15999,
        stock: 30,
        category: 'Furniture',
        brand: 'Wakefit',
        featured: true,
        rating: 4.6,
        numReviews: 234,
        image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400&q=80',
        color: 'White',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Nilkamal Plastic Chair (Set of 2)',
        description: 'Molded plastic, stackable, lightweight, suitable for home/office.',
        price: 3499,
        stock: 100,
        category: 'Furniture',
        brand: 'Nilkamal',
        featured: false,
        rating: 4.2,
        numReviews: 345,
        image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400&q=80',
        color: 'Blue',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Godrej Eon 2-Door Steel Almirah',
        description: 'Durable steel construction, 4 shelves, lockable handle.',
        price: 15999,
        stock: 15,
        category: 'Furniture',
        brand: 'Godrej',
        featured: false,
        rating: 4.4,
        numReviews: 89,
        image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400&q=80',
        color: 'Grey',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Urban Ladder Leo Study Chair',
        description: 'Ergonomic mesh back, adjustable height, castor wheels.',
        price: 8999,
        stock: 25,
        category: 'Furniture',
        brand: 'Urban Ladder',
        featured: false,
        rating: 4.5,
        numReviews: 56,
        image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400&q=80',
        color: 'Black',
        size: null,
        fabric: 'Mesh',
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Pepperfry Solid Wood Coffee Table',
        description: 'Sheesham wood, rustic finish, spacious tabletop.',
        price: 12999,
        stock: 12,
        category: 'Furniture',
        brand: 'Pepperfry',
        featured: false,
        rating: 4.3,
        numReviews: 34,
        image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400&q=80',
        color: 'Brown',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },

      // ---------- Additional 5 Home Products ----------
      {
        name: 'Honeywell Air Purifier (HPA300)',
        description: 'For large rooms, 3-in-1 HEPA filter, 4 fan speeds.',
        price: 24999,
        stock: 12,
        category: 'Home',
        brand: 'Honeywell',
        featured: true,
        rating: 4.6,
        numReviews: 78,
        image: 'https://images.unsplash.com/photo-1584269600521-3b1b3c2b6b6b?w=400&q=80',
        color: 'White',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Kent Grand Plus RO Water Purifier',
        description: '7-stage purification, UV & UF, mineral retention technology.',
        price: 18999,
        stock: 20,
        category: 'Home',
        brand: 'Kent',
        featured: true,
        rating: 4.5,
        numReviews: 312,
        image: 'https://images.unsplash.com/photo-1584269600521-3b1b3c2b6b6b?w=400&q=80',
        color: 'White',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Philips HL1643 Mixer Grinder (750W)',
        description: '4 stainless steel jars, turbo boost, fruit filter.',
        price: 5999,
        stock: 50,
        category: 'Home',
        brand: 'Philips',
        featured: false,
        rating: 4.5,
        numReviews: 267,
        image: 'https://images.unsplash.com/photo-1584269600521-3b1b3c2b6b6b?w=400&q=80',
        color: 'Black',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Bajaj Flashy 1200W Dry Iron',
        description: 'Non-stick coating, 360° swivel cord, thermostat control.',
        price: 799,
        stock: 200,
        category: 'Home',
        brand: 'Bajaj',
        featured: false,
        rating: 4.2,
        numReviews: 567,
        image: 'https://images.unsplash.com/photo-1584269600521-3b1b3c2b6b6b?w=400&q=80',
        color: 'Blue',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
      {
        name: 'Prestige PFTGM 01 Gas Stove (4 Burner)',
        description: 'Toughened glass top, brass burners, auto-ignition.',
        price: 6999,
        stock: 30,
        category: 'Home',
        brand: 'Prestige',
        featured: false,
        rating: 4.4,
        numReviews: 89,
        image: 'https://images.unsplash.com/photo-1584269600521-3b1b3c2b6b6b?w=400&q=80',
        color: 'Black',
        size: null,
        fabric: null,
        occasion: null,
        gender: 'Unisex',
      },
    ];

    await Product.bulkCreate(products);
    console.log('✅ Seeding complete! 50 products added.');
    console.log('📊 Total products:', products.length);
    console.log('👤 Admin: admin@shopwave.com / admin123');
    console.log('👤 User: user@shopwave.com / user123');
  } catch (error) {
    console.error('❌ Seed error:', error.message);
  }
};

module.exports = seedData;